### ISSUE TITLE
Get the resolution of the original stream

### ISSUE THREAD

**Issue by Adler-lug** [jpenny1993/RtspViewer#1]
Hello.
How can I get the resolution of the original stream?

**Comment by jpenny1993** [comment]
Hi,

You would need to decode the RTSP frame into an image before you can get the original resolution. This is done in **FFmpegVideoDecoder.cs** which updates the frame buffer and outputs the image dimensions.

```
resultCode = FFmpegVideoPInvoke.DecodeFrame(_decoderHandle, (IntPtr)rawBufferPtr,
                    rawVideoFrame.FrameSegment.Count,
                    out int width, out int height, out FFmpegPixelFormat pixelFormat);
```

This project is based off of a sample project provided by the creator of RtspClientSharp, the video decoder is not my own work.
https://github.com/BogdanovKirill/RtspClientSharp/tree/master/Examples/SimpleRtspPlayer

**Comment by Adler-lug** [comment]
Thanks for the hint, but I don’t understand how I can get it in the class VideoView.
The point is that I want to automatically adjust the aspect ratio of the VideoView respecting the aspect ratio of the original video.
Some cameras have different aspect ratios and I want the picture to be correct.

**Comment by jpenny1993** [comment]
Add Width and Height properties to `IDecodedVideoFrame`, the DecodedVideoFrame object is propagated all the way to the VideoView control via the FrameReceived event on the video source.

**Comment by Adler-lug** [comment]
Thank you. I'll try to figure it out.

**Comment by jpenny1993** [comment]
I'd have done it sooner but I was working.
See this commit https://github.com/jpenny1993/RtspViewer/commit/04ed4273fcab130c95a0e2eb821f61db26a265eb

**Comment by Adler-lug** [comment]
It's good. Thanks.
